### PR TITLE
fix IE8 does not pass event object

### PR DESCRIPTION
**Pull request by ImBobby**
This PR should fix issue #22 
[Reference](http://stackoverflow.com/questions/16399150/onkeydown-and-onkeyup-events-dont-work-on-internet-explorer-8)

### CODE REVIEW

**Comment by leandroadacosta** [comment]
@ImBobby should? Did you test it?

**Comment by ImBobby** [comment]
Yes I did using real IE8 win XP.

**Comment by vsalbuq** [comment]
Working here! IE8 on Windows XP too! Thank you very much @ImBobby !!!

**Comment by leandroadacosta** [comment]
\o/! and the others browsers and mobile browsers, are ok? :) I did not test yet =/

**Comment by ImBobby** [comment]
I'm on it.

**Comment by vsalbuq** [comment]
@leandroadacosta I can't test on other devices now, but I think the "or" on the variable does the magic. It receives another value only if it came null.

**Comment by ImBobby** [comment]
I ran test via BrowserStack to these following browsers:
* Android Browser 2.2
* Android Browser 2.3
* Opera Mobile 10
* iOS Safari 3.2
* Windows Phone Browsers
* IE9

The test case was `VMasker(elem).maskPattern('999-SSS')` and all those browsers work as expected. I tested on the lowest browser support and theoretically newer browsers will work just fine.

**Comment by leandroadacosta** [comment]
Great guys! Thanks. I will merge it :+1: :metal: :metal:

**Pull request merged**
