### PR TITLE
add sample - Dynamic mask

### PR DESCRIPTION
**Pull request by lagden**

### CODE REVIEW

**Comment by grsabreu** [comment]
Any updates on this?

**Comment by leandroadacosta** [comment]
Hi @lagden, great. We will review it until this weekend. cc @grsabreu

**Comment by lagden** [comment]
Ok!! But I think this one is more important: https://github.com/BankFacil/vanilla-masker/pull/56

When you run the command:
```
$ gzip --best example.js
```
The output is:  `example.js.gz`

**Comment by ivanbanov** [comment]
I think that better than a documentation teaching how to create a dynamic mask it could be a default behavior :thought_balloon:

**Comment by leandroadacosta** [comment]
@lagden sorry for my late, but your "doc code" to solve this problem is nice.

**Comment by lagden** [comment]
:metal:

**Comment by gabrielpugliese-luizalabs** [comment]
Thanks! :clap: :clap: :clap: :clap: :clap:

**Pull request merged**
